### PR TITLE
Rewrote using functional component and hook. Fix dependencies and build. add link argument

### PR DESCRIPTION
**Pull request by cshuphys**
The original front end dependency is broken thus can't be build. 
I fix the dependency, rewrite the frontend using functional component and hook. I also fix the gitignore so that node_module is ignored and removed. 
In addition, I add a new argument as link. So that when it opens a new window of that link when double click on any node. 

Please review, thank!

### CODE REVIEW

**Comment by Uddhav07** [comment]
hello sir, can you add empty build folder inside frontend folder since streamlit channged its code and it requires that folder somehow

also theres this font function that is ther in node and edges which can be added 
tysm

**Comment by Uddhav07** [comment]
when pulling with pip install git+ the frontend doesnt get added idk why
if added manually, original works but in this the component doenst work

**Comment by Uddhav07** [comment]
also is there any way to auto beautufi the node arrandement, its pretty bad by default

**Comment by cshuphys** [comment]
I only upload the src code. I didn't build it in this case so you can't just simply use pip + git to use it. I think @ChrisDelClea can merge it and build it via some CI pipeline so that you can directly use it that way. 
If you wanna build it, simply do `npm install` and `npm build` at the front end directory. Then you should be able to use it.

**Comment by cshuphys** [comment]
@ChrisDelClea Do we have plan to pull this change I made? I didn't follow up this closely. Not sure if there is anything else you might need from my side.

**Comment by ChrisDelClea** [comment]
Amazing work, well done!

**Comment by cshuphys** [comment]
I am not familiar with your build CI pipeline setup. Would it auto build front end so that when we do pip install it will use the new version?

**Pull request merged**
