### PR TITLE
Pass Click Values to Python

### PR DESCRIPTION
**Pull request by conradbez**
#12 

Passes dictionary back to streamlit in the form

`{"action" : "ACTION_COMPLETED_BY_USER" , "node" : NodeID }`

or

`{"action" : "ACTION_COMPLETED_BY_USER" , "sourceNode" : NodeID , "targetNode" : NodeID }`

Todo - might want to consider a better interface to record actions etc.

### CODE REVIEW

**Comment by ChrisChross** [comment]
xxx

**Comment by JuanFMontesinos** [comment]
Hey
How to make use of this feature?
Where does streamlit save the info.

**Comment by ChrisChross** [comment]
Good Question, that's why i was asking for an example :)

**Comment by ChrisChross** [comment]
I guy you can basically get it from agraph. But have to test it too.

```python 
clicked_node = agraph()
```

**Comment by brandaobrandisborges** [comment]
Hello everyone. Anysolutions?

**Pull request merged**
